server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka

zuul:
  routes:
    department:
      path: /department/**
      serviceId: department-service
    organization:
      path: /organization/**
      serviceId: organization-service
    employee:
      path: /employee/**
      serviceId: employee-service